server:
  port: 8090
  
spring:
  application.name: gateway
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      - id: downvotes
        uri: http://localhost:8083
        predicates:
        - Path=/downvotes/**
      - id: upvote
        uri: http://localhost:8083
        predicates:
        - Path=/upvote/**
      - id: users
        uri: http://localhost:8081
        predicates:
        - Path=/users/**
      - id: responses
        uri: http://localhost:8082
        predicates:
        - Path=/responses/**
      - id: post
        uri: http://localhost:8085
        predicates:
        - Path=/post/**
      - id: locations
        uri: http://localhost:8085
        predicates:
        - Path=/locations/**